-- phpMyAdmin SQL Dump
-- version 3.5.1
-- http://www.phpmyadmin.net
--
-- Хост: 127.0.0.1
-- Время создания: Дек 12 2016 г., 02:13
-- Версия сервера: 5.5.25
-- Версия PHP: 5.3.13

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- База данных: `articles`
--
CREATE DATABASE `articles` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `articles`;

-- --------------------------------------------------------

--
-- Структура таблицы `list_article`
--

CREATE TABLE IF NOT EXISTS `list_article` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `date` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `text_article` longtext NOT NULL,
  `src` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=24 ;

--
-- Дамп данных таблицы `list_article`
--

INSERT INTO `list_article` (`id`, `date`, `title`, `description`, `text_article`, `src`) VALUES
(1, 1481500104, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_1.jpeg'),
(2, 1481500108, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_2.jpeg'),
(3, 1481500111, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_3.jpeg'),
(4, 1481500114, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_4.jpeg'),
(5, 1481500117, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_5.jpeg'),
(6, 1481500121, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_6.jpeg'),
(7, 1481500124, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_7.jpeg'),
(8, 1481500126, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_8.jpeg'),
(9, 1481500129, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_9.jpeg'),
(10, 1481500132, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_10.jpeg'),
(11, 1481500134, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_11.jpeg'),
(12, 1481500208, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_12.jpeg'),
(13, 1481500212, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_13.jpeg'),
(14, 1481500215, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_14.jpeg'),
(15, 1481500218, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_15.jpeg'),
(16, 1481500221, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_16.jpeg'),
(17, 1481500670, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_17.jpeg'),
(18, 1481500673, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_18.jpeg'),
(19, 1481500677, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_19.jpeg'),
(20, 1481500680, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_20.jpeg'),
(21, 1481500683, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_21.jpeg'),
(22, 1481500686, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_22.jpeg');
INSERT INTO `list_article` (`id`, `date`, `title`, `description`, `text_article`, `src`) VALUES
(23, 1481501131, 'Типы', 'Для хранения различных данных в языках программирования используют переменные. Переменной называется область памяти, имеющая имя.', 'PHP поддерживает восемь простых типов.\r\n\r\nЧетыре скалярных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;boolean&lt;/li&gt;\r\n&lt;li&gt;integer&lt;/li&gt;\r\n&lt;li&gt;float (число с плавающей точкой, также известное как double)&lt;/li&gt;\r\n&lt;li&gt;string&lt;/li&gt;\r\n&lt;/ul&gt;\r\nТри смешанных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;array&lt;/li&gt;\r\n&lt;li&gt;object&lt;/li&gt;\r\n&lt;li&gt;callable&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ, наконец, два специальных типа:\r\n&lt;ul&gt;\r\n&lt;li&gt;resource&lt;/li&gt;\r\n&lt;li&gt;NULL&lt;/li&gt;\r\n&lt;/ul&gt;\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n\r\nДля удобства понимания в этом руководстве используется также несколько псевдотипов:\r\n&lt;ul&gt;\r\n&lt;li&gt;mixed&lt;/li&gt;\r\n&lt;li&gt;number&lt;/li&gt;\r\n&lt;li&gt;callback (он же callable)&lt;/li&gt;\r\n&lt;li&gt;array|object&lt;/li&gt;\r\n&lt;li&gt;void&lt;/li&gt;\r\n&lt;/ul&gt;\r\nИ псевдопеременная $....\r\n\r\nВы также можете найти несколько упоминаний типа двойной точности (double). Рассматривайте его как число с плавающей точкой, два имени существуют только по историческим причинам.\r\n\r\nКак правило, программист не устанавливает тип переменной; обычно это делает PHP во время выполнения программы в зависимости от контекста, в котором используется переменная.', './files/article_23.jpeg');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
